nexus_volume_capacity: 10Gi
nexus_max_memory: 2Gi
nexus_min_memory: 512Mi
nexus_max_cpu: 1
nexus_min_cpu: 200m

nexus_service_name: nexus

nexus_image_version: 3.7.1

project_name: nexus
project_display_name: Nexus
project_desc: Nexus Repository Manager
# project_annotations:

openshift_cli: oc

ephemeral: false